import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
// import "../styles/globals.css";
import "../../styles/globals.css";
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import "react-toastify/dist/ReactToastify.css";
import Header from "@/ui/Header";
import HeaderBottom from "@/ui/HeaderBottom";
import Layout from "@/ui/Layout";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amazon.com. Spend less. Smile more.",
  description: "Generated by Lutfor Rahman Hira",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" font-Montserrat bg-slate-300">
        <Layout>
          <Header />
          <HeaderBottom />
          {children}
        </Layout>
      </body>
    </html>
  );
}
